apiVersion: v1
kind: PersistentVolume
metadata:
  name: tcl-pv
  namespace: tcl
spec:
  storageClassName: local-storage
  capacity:
    storage: 5Gi
  # volumeMode field requires BlockVolume Alpha feature gate to be enabled
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  local:
    path: 'D:\'  # use c:\ after path translation or `c:\dir` 'D:\tcl-ide-sunflower-64bit\/data'
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop
---
apiVersion: v1
kind : PersistentVolumeClaim
metadata:
  name: tcl-pvc
  namespace: tcl
spec:
  storageClassName: local-storage
  volumeName: tcl-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5G